name:                 logicsim
version:              0.1.0.0
visibility:           public
id:                   logicsim-0.1.0.0-inplace
key:                  logicsim-0.1.0.0-inplace
abi:                  inplace
exposed:              True
exposed-modules:
    Logic.Bit Logic.Byte Logic.CPU Logic.Circuits Logic.Classes
    Logic.Gates Logic.Memory Logic.Types Logic.Utils

import-dirs:
    /home/andrewcrowe/projects/Haskell/logicsim/dist-newstyle/build/x86_64-linux/ghc-9.6.7/logicsim-0.1.0.0/build

library-dirs:
    /home/andrewcrowe/projects/Haskell/logicsim/dist-newstyle/build/x86_64-linux/ghc-9.6.7/logicsim-0.1.0.0/build

library-dirs-static:
    /home/andrewcrowe/projects/Haskell/logicsim/dist-newstyle/build/x86_64-linux/ghc-9.6.7/logicsim-0.1.0.0/build

dynamic-library-dirs:
    /home/andrewcrowe/projects/Haskell/logicsim/dist-newstyle/build/x86_64-linux/ghc-9.6.7/logicsim-0.1.0.0/build

data-dir:             /home/andrewcrowe/projects/Haskell/logicsim/.
hs-libraries:         HSlogicsim-0.1.0.0-inplace
depends:              base-4.18.3.0 mtl-2.3.1
haddock-interfaces:
    /home/andrewcrowe/projects/Haskell/logicsim/dist-newstyle/build/x86_64-linux/ghc-9.6.7/logicsim-0.1.0.0/doc/html/logicsim/logicsim.haddock

haddock-html:
    /home/andrewcrowe/projects/Haskell/logicsim/dist-newstyle/build/x86_64-linux/ghc-9.6.7/logicsim-0.1.0.0/doc/html/logicsim
